### ISSUE TITLE
Respect text scale (font size) system settings in UI

### ISSUE THREAD

**Issue by franklinbill** [sadr0b0t/yashlang#72]
Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, in the first page, the text in the red box is half blocked. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
I hope that the page can be set to scroll, so that the problem caused by the display size of large can be solved.
App version is 0.5.0, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
<img width="446" alt="bug-yashlang" src="https://user-images.githubusercontent.com/18572115/103148585-47341d00-479c-11eb-907e-df6fb8a67a49.png">

**Comment by sadr0b0t** [comment]
thank's for reporting. Never used this option, so did not notice this issue.

Some technical info: https://code.tutsplus.com/tutorials/android-user-interface-design-basic-font-sizes--mobile-11194

Initial support for text scaling system option is to use "sp" (scalable points) instead of "dp" (device-independent pixels) for scalable text (as it was).

The fix here is to use "sp" not only for text, but also for some other ui elements (for image size in most cases), so upscaled text won't be cut. Another hint with this patch is that "sp" is only used for image height, but not for image width, so image height (along with list element height) would grow with text, but won't take the whole screen width when upscaled.

This fixed version with this patch would be released as 0.6.0, probably, soon, please, check. Also feel free to report similar issues if you find them in some other places here.

the fix: https://github.com/sadr0b0t/yashlang/commit/1c861bd7b9d1ac83a1810edbfae684b76863e7cc

![Screenshot_2021-01-20-21-10-13-306_su sadrobot yashlang](https://user-images.githubusercontent.com/1653222/105218887-cd0e7280-5b66-11eb-9371-0949fca012e5.png)
![Screenshot_2021-01-20-21-13-44-465_su sadrobot yashlang](https://user-images.githubusercontent.com/1653222/105218890-ced83600-5b66-11eb-9228-8062a15c9077.png)
